### ISSUE TITLE
Google Maps API v3 Compatibility

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kokuda/gpxviewer#5]
```
The current version isn't compatible with v3 of the maps API. I've updated it 
in a repository hosted at GitHub: http://christopherpeplin.com/posts/gpxviewer/
```

Original issue reported on code.google.com by `chris.pe...@gmail.com` on 29 May 2011 at 3:31

**Comment by kokuda** [comment]
I have now updated the script to using the Google Maps V3 API.  Wish I saw this comment first, it would have saved some time ;-)
