### ISSUE TITLE
Remove GPX

### ISSUE THREAD

**Issue by tourenfex** [kokuda/gpxviewer#7]
How can I remove the gpx-overlay on mouseout-event?

**Comment by kokuda** [comment]
I'm not sure what you mean?  Do you mean making the popups close after moving the mouse away from them?  The google.maps.InfoWindow that is used can be closed by calling .close(), but I'm not sure how to decide when that should happen.

You can define a custom popup with more flexibility that can probably do what you want.  See the documentation here https://developers.google.com/maps/documentation/javascript/examples/overlay-popup.

Unfortunately, support for this is not available in loadgpx.js as it is.  It can be considered for future updates, however, it is most likely that the new feature would be adding support for the custom overlays as described in the link above so it is best to start there.

Feel free to publish your changes and submit a pull request.
